default:
  target: dev
  outputs:
    prod:
      type: snowflake
      account: ""
      user: ""
      database: "{{ env_var('DBT_TARGET_DB') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA') }}"
      warehouse: "{{ env_var('DBT_TARGET_WH') }}"
      role: "{{ env_var('DBT_TARGET_ROLE') }}"
      threads: 4
    dev:
      type: snowflake
      account: "WHB86050-SARACUS_PARIS"
      user: "homa_svc"
      private_key_path: '../rsa_key.p8'
      database: "{{ env_var('DBT_TARGET_DB', 'HOMA_DB') }}"
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'DBT_MHOFFHUES') }}"
      warehouse: "{{ env_var('DBT_TARGET_WH', 'HOMA_WH') }}"
      role: "{{ env_var('DBT_TARGET_ROLE', 'ACCOUNTADMIN') }}"
      threads: 4
